CREATE TABLE lab_master (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lab_select VARCHAR(255) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE lab_details ( 
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    lab_select_id INT UNSIGNED NOT NULL, 
    lab_details VARCHAR(255) NOT NULL,
    normal_range VARCHAR(255), 
    unit VARCHAR(255), 
    price VARCHAR(255), 
    child VARCHAR(255), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);



INSERT INTO lab_master (lab_select, DESCRIPTION, created_at, updated_at) VALUES
('Haematology', NULL, NOW(), NOW()),
('Bio-Chemistry', NULL, NOW(), NOW()),
('Urine Analysis', NULL, NOW(), NOW()),
('Motion Analysis', NULL, NOW(), NOW()),
('Liver Function Test', NULL, NOW(), NOW()),
('Enzymes Assay', NULL, NOW(), NOW()),
('Electrolytes', NULL, NOW(), NOW()),
('Lipid Profile', NULL, NOW(), NOW()),
('Immuno Serology', NULL, NOW(), NOW()),
('Culture & Drug Sensitivity', NULL, NOW(), NOW()),
('Fluid Analysis', NULL, NOW(), NOW()),
('Coagulation Assay', NULL, NOW(), NOW()),
('Sputum Analysis', NULL, NOW(), NOW()),
('Semen Analysis', NULL, NOW(), NOW()),
('Endocrinology', NULL, NOW(), NOW()),
('1.5T M.R.I Study', NULL, NOW(), NOW()),
('Breast Imaging', NULL, NOW(), NOW()),
('64 Slice C.T. Angiography', NULL, NOW(), NOW()),
('C. T. Study', NULL, NOW(), NOW()),
('Ultrasound Study', NULL, NOW(), NOW()),
('Doppler Studies', NULL, NOW(), NOW()),
('Other Studies', NULL, NOW(), NOW());



INSERT INTO lab_details (lab_select_id, lab_details, normal_range, unit, price, child)
SELECT 
    FLOOR(1 + (RAND() * 22)),  -- Generates a random number between 1 and 22
    CONCAT('Lab Detail ', FLOOR(1 + RAND() * 100)), -- Random lab detail name
    CONCAT(FLOOR(1 + RAND() * 100), '-', FLOOR(101 + RAND() * 200)), -- Random normal range
    CONCAT('Unit ', FLOOR(1 + RAND() * 10)), -- Random unit
    ROUND(RAND() * 1000, 2), -- Random price
    CONCAT('Child ', FLOOR(1 + RAND() * 50)) -- Random child value
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION 
      SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION 
      SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION 
      SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION 
      SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION 
      SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION 
      SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION 
      SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION 
      SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION 
      SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION 
      SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION 
      SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION 
      SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION 
      SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION 
      SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION 
      SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80) AS tmp;
