CREATE TABLE symptom_diseases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symptom VARCHAR(255),
    disease VARCHAR(255)
);


INSERT INTO `symptom_diseases` (`disease`, `symptom`) VALUES
('Tiredness', 'Idiopathic pulmonary fibrosis, Crohn’s disease, Insomnia, Iron deficiency anaemia, Reactive arthritis, Respiratory syncytial virus, Rheumatoid arthritis,Oesophageal cancer,Ewing sarcoma, Ewing sarcoma: Children, Flu, Heart failure, Hepatitis A, Hepatitis B, HIV, Hyperglycaemia (high blood sugar), Hypoglycaemia (low blood sugar),Lung Carcinoid Tumour, Stomach Carcinoid Tumour, Carcinoid Tumour, Chronic Fatigue Syndrome, Chronic Kidney Disease, Chronic Lymphocytic Leukaemia, Chronic Myeloid Leukaemia, Cirrhosis, Cardiovascular Disease, Cervical Cancer, Acute lymphoblastic leukaemia: Children, Atrial fibrillation, Bone cancer: Teenagers and young adults, Bronchitis, kidney infection,Lung Carcinoid Tumour, Stomach Carcinoid Tumour, Carcinoid Tumour, Chronic Fatigue Syndrome, Chronic Kidney Disease, Chronic Lymphocytic Leukaemia, Chronic Myeloid Leukaemia, Cirrhosis, Cardiovascular Disease, Cervical Cancer'),
('shortness of breath,', 'Idiopathic pulmonary fibrosis,Food Allergy, Heart Attack, Heart block, Heart palpitation, High blood pressure, High cholesterol, Aplastic anaemia, Lung cancer, Vitamin B12 or Folate Deficiency Anaemia, mesothelioma, wolff-parkinson, white syndrome, Wolff-Parkinson-White Syndrome'),
('loss of appetite', 'Idiopathic pulmonary fibrosis, Respiratory syncytial virus, Oesophageal cancer, ovarian cancer:Teenagers and young adults,Yellow fever, kidney infection, Carcinoid Syndrome, Chronic Kidney Disease, Chronic Pancreatitis, Cirrhosis, Cervical Cancer,Food Poisoning, Gallstones, Hand, foot and mouth disease, Hepatitis A, Hepatitis B, Non-Hodgkin lymphoma: Children, Acute cholecystitis, alcohol-related liver disease, Appendicitis, Bone cancer: Teenagers and young adults, Neuroblastoma: Children, Lyme tumours, vomiting in adults'),
('a persistent dry cough', 'Idiopathic pulmonary fibrosis, Asbestosis, Lung cancer'),
('Breathlessness,', 'Cold and flu symptoms in babies, Cold and flu symptoms in children, Inherited heart conditions,obesity, Heart failure, Hodgkin lymphoma, acute lymphoblastic leukaemia, acute myeloid leukaemia, Acute myeloid leukaemia: Teenagers and young adults, Asthma, Atrial fibril, Artial fibrillation, Kaposi’s sarcoma, Lung Carcinoid Tumour, Carcinoid Tumour, Carcinoid Syndrome, Cardiovascular Disease, Chronic Obstructive Pulmonary Disease (COPD), Coronavirus (COVID-19), Congenital Heart Disease, Cirrhosis, Carcinoid Crisis'),
('Cough', 'Cold and flu symptoms in babies, Cold and flu symptoms in children, Respiratory syncytial virus,Oesophageal cancer, neuroendocrine tumours, bronchiectasis, Measles, Mesothelioma, Laryngeal(larynx) cancer, measles, mesothelioma'),
('runny nose', 'Cold and flu symptoms in children, Respiratory syncytial virus, Allergic rhinitis, Allergies, Measles, whooping cough'),
('high temperature (fever)', 'Impetigo, Reactive arthritis, Rheumatoid arthritis, Acute cholecystitis, Anxiety, Appendicitis,Meningitis'),
('red sores', 'Impetigo'),
('swollen glands', 'Impetigo'),
('Vomiting', 'Indigestion, norovirus, Acute cholecystitis, Appendicitis, Brain tumour, Brain tumours: Children, Brain tumours: Teenagers and young adults,liver cancer,liver disease,lyme tumours,malaria,whooping cough, Urinary tract infection (UTI) in children'),
('(nausea)', 'Indigestion, ovarian cancer,  Acute cholecystitis,Vertigo, vomiting in adults, Malaria, Malignant Brain Tumor, Meningitis, Migraine, Minor Head Injury, Wilm’s Tumour,Molar pregnancy,liver disease'),
('Discomfort In upper abodomen', 'Indigestion'),
('Bleeding', 'Ingrown toenail, Aplastic anaemia,vulval cancer'),
('overgrowth of skin', 'Ingrown toenail'),
('inflammation of the skin', 'Ingrown toenail'),
('white or yellow pus coming from the affected area', 'Ingrown toenail'),
('diarrhoea', 'Crohn’s disease, Ulcerative colitis, Irritable bowel syndrome, Reactive arthritis,  neuroendocrine tumours,acute pancreatitis,  Bowel polyps,Lactose intolerance, Carcinoid Syndrome, Clostridium Difficile, Coeliac Disease, Crohn’s Disease, Cholera'),
('abdominal pain', 'Crohn’s disease, Ulcerative colitis, Reactive arthritis, ovarian cancer ,ovariancancer:Teenagers and young adults,recurrent miscarriage, Pancreatic cancer, Pelvic inflammatory disease, Polycystic ovary syndrome (PCOS), Appendicitis, Bile duct cancer(cholangiocarcinoma), Bowel polyps, diverticulitis'),
('joint pain', 'Crohn’s disease, osteoarthritis of the knee,obesity, Rare Conditions, Arthritis,lupus, Zika virus, Joint hypermobility, Kaposi’s sarcoma, Cervical Spondylosis, Crohn’s Disease, Carpal Tunnel Syndrome'),
('mouth ulcers', 'Crohn’s disease, Ulcerative colitis, Iron deficiency anaemia,\nReactive arthritis'),
('Runny nose', 'Measles,whooping cough'),
('painful and swollen joints', 'Ulcerative colitis'),
('Stiff neck', 'Meningitis'),
('chest pain', 'Inherited heart conditions, Aplastic anaemia,Mesothelioma, Kaposi’s sarcoma, Lung Carcinoid Tumour, Carcinoid Syndrome, Carcinoid Tumour, Cardiovascular Disease, Chest Infection, Costochondritis, Coronary Heart Disease'),
('dizzy spells', 'Inherited heart conditions'),
('vertigo', 'Meniere’s disease'),
('Hot flashes', 'Menopause'),

('Palpitations', 'Inherited heart conditions, Atrial fibrillation'),
('hard to fall asleep', 'Insomnia'),
('wake up several times during the night', 'Insomnia'),
('weight loss', 'Idiopathic pulmonary fibrosis, Reactive arthritis, Rheumatoid arthritis, Oesophageal cancer,rare tumours,  Non-Hodgkin lymphoma, alcohol-related liver disease,mouth cancer,liver cancer, Threadworms,Diarrhoea, Stomach Carcinoid Tumour'),
('hair loss', 'Iron deficiency anaemia'),
('feeling itchy', 'Iron deficiency anaemia, Allergies,Lichen planus'),
('headache', 'Iron deficiency anaemia, Neck injury, norovirus, Acute lymphoblastic leukaemia: Teenagers and young adults, Acute myeloid leukaemia: Teenagers and young adults, Anxiety, Aplastic anaemia, Brain tumour, Brain tumours: Children, Brain tumours: Teenagers and young adults, Bronchitis,Malignant Brain Tumor,Meningitis,migraine,Labyrinthitis'),
('(heart palpitations', 'Iron deficiency anaemia'),
('spoon-shaped nails', 'Iron deficiency anaemia'),
('shortness of breath', 'Iron deficiency anaemia,Lung cancer, Vitamin B12 or Folate Deficiency Anaemia, mesothelioma, wolff-parkinson, white syndrome'),
('feeling sick', 'Irritable bowel syndrome, Norovirus, alcohol-related liver disease,Low blood pressure,Lyme tumours,liver cancer\nle bowel syndrome'),
('Heartburn', 'Irritable bowel syndrome'),
('swelling of your stomach', 'Irritable bowel syndrome'),
('constipation', 'Irritable bowel syndrome, Rhabdomyosarcoma, neuroendocrine tumours, Bowel polyps, Joint hypermobility, diverticulitis, Bowel Carcinoid Tumour, Cervical Spondylosis, Chronic Pain, Crohn’s Disease, Chronic Kidney Disease'),
('lack of energy (lethargy)', 'Irritable bowel syndrome,  Acute lymphoblastic leukaemia: Children, Acute myeloid leukaemia: Children'),
('Swelling', 'Reactive arthritis, Rheumatoid arthritis,Osteoarthritis of the thumb, otitis externa,  Achilles tendinopathy,ankle sprain, Ankle avulsion fracture, Bone Cancer, Bunion(halluxvalgus),liver disease,Varicose Eczema, varicose veins, venous leg ulcer, managing gential symptoms, metacarpal fracture, wrist fracture,Wilm’s tumour, Tick bites, Deep vein thrombosis'),
('Stiffness', 'Reactive arthritis, Rheumatoid arthritis,Rare Conditions'),
('eye pain, eye problem', 'Reactive arthritis, Brain tumours: Children, Brain tumours: Teenagers and young adults'),
('Redness', 'Reactive arthritis, Rheumatoid arthritis, otitis externa ,oral thrush in adults, itchy skin,Itching, Ankle sprain'),
('or discharge from the penis or vagina', 'Reactive arthritis'),
('pain when peeing', 'Reactive arthritis'),
('shortness of breath', 'Respiratory syncytial virus'),
('wheezing', 'Respiratory syncytial virus, Allergies, Asthma, Asbestosis, Lung Carcinoid Tumour, Carcinoid Syndrome, Carcinoid Tumour, Chronic Obstructive Pulmonary Disease (COPD), Coronavirus (COVID-19), Croup'),
('sweating', 'Rheumatoid arthritis, Acute cholecystitis'),
('a poor appetite', 'Rheumatoid arthritis'),
('heat around the joints', 'Rheumatoid arthritis'),
('silvery rash on your skin', 'Ringworm and other fungal infections'),
('inflamed skin', 'Ringworm and other fungal infections'),
('Skin red and irritated', 'Ringworm and other fungal infections'),
('itchy scalp', 'Fungal scalp infection'),
('patchy hair loss', 'Fungal scalp infection'),
('Itching', 'Rosacea, Atopic eczeme'),
('thickened skin', 'Rosacea'),
('flushing', 'Rosacea'),
('facial swelling', 'Rosacea'),
('rough skin', 'Rosacea'),
('red patches', 'Rosacea'),
('Anxiety', 'Obsessive compulsive disorder, Alzheimer’s disease'),
('loud snoring', 'Obstructive sleep apnoea'),
('sleepy during the day', 'Obstructive sleep apnoea'),
('breathing pauses through the night', 'Obstructive sleep apnoea'),
('repeated period', 'Obstructive sleep apnoea'),
('Difficult swallowing', 'Oesophageal cancer,Rare Conditions'),
('persistent vomiting', 'Oesophageal cancer'),
('hoarseness', 'Oesophageal cancer'),
('Persistent heartburn', 'Oesophageal cancer'),
('vomiting blood', 'Oesophageal cancer,  alcohol-related liver disease'),
('Pain upper tummy', 'Oesophageal cancer'),
('joint tenderness', 'Osteoarthritis'),
('loss of muscle bulk', 'Osteoarthritis'),
('stiffness in joints', 'Osteoarthritis,  Arthritis, Back problems'),
('limited range of movement in joints', 'Osteoarthritis'),
('stiffness in hip', 'Osteoarthritis of the hip'),
('difficulty in daily activities such as walking', 'Osteoarthritis of the hip'),
('weakness in the buttock muscles', 'Osteoarthritis of the hip'),
('pain in or around the hip joint', 'Osteoarthritis of the hip'),
('swelling in the joint.', 'Osteoarthritis of the knee'),
('weakness in the thigh muscle.', 'Osteoarthritis of the knee'),
('stiffness in the knee', 'Osteoarthritis of the knee'),
('crunching noises', 'Osteoarthritis of the knee'),
('pain', 'Osteoarthritis of the thumb, Neck problems,ankle sprain, Ankle avulsion fracture,ankylosing spondylitis, Bone cancer: Teenagers and young adults,Bunion(halluxvalgus'),
('reduced ability to grip', 'Osteoarthritis of the thumb'),
('loss of movement around the thumb and wrist', 'Osteoarthritis of the thumb'),
('Pain in the bone', 'Osteosarcoma, Acute lymphoblastic leukaemia: Teenagers and young adults, Acute myeloid leukaemia: Children, Acute myeloid leukaemia: Teenagers and young adults'),
('Swelling around the bone', 'Osteosarcoma'),
('Persistent bone pain', 'Osteosarcoma'),
('Limping', 'Osteosarcoma'),
('ear pain', 'otitis externa'),
('tenderness', 'otitis externa, Ankle avulsion fracture, Deep vein thrombosis, dehydration'),
('Sore glands', 'otitis externa'),
('discharge from ear', 'otitis externa'),
('soreness', 'oral thrush in adults,Itchy Bottom'),
('difficulty eating', 'ovarian cancer'),
('persistent pelvic pain', 'ovarian cancer'),
('increased abdominal size', 'ovarian cancer'),
('back pain', 'ovarian cancer ,obesity, osteoporosis'),
('pain during sex', 'ovarian cancer , Ovarian cyst'),
('difficulty having a poo', 'Ovarian cyst'),
('a frequent need to urinate', 'Ovarian cyst'),
('difficulty getting pregnant', 'Ovarian cyst'),
('Irregular periods', 'Ovarian cyst,infertility'),
('Regular periods', 'Ovarian cyst, Anorexia nervosa'),
('Pelvic pain', 'Ovarian cyst,Infertility, Pelvic inflammatory disease, Pelvic organ prolapse, Polycystic ovary syndrome (PCOS),Vaginal cancer, womb(uterus)cancer'),
('Hyperactivity', 'Overactive thyroid'),
('muscle weakness', 'Overactive thyroid, Addison’s disease,Arterial Thrombosis,Motor neurone disease(MND), multiple sclerosis(MS), muscular dystrophy, Myasthenia gravis'),
('Fatigue', 'Overactive thyroid,Rare Conditions,rare tumours, Pulmonary hypertension, Non-alcoholic fatty liver disease (NAFLD),Aplastic anaemia, Asbestosis, Ataxia, bronchiectasis, Neuroblastoma: Children, Addison’s disease,Lupus, liver disease, lung cancer, vitamin B12 or Folate deficienct anaemia, malaria, malnutrition, mesothelioma, multiple sclerosis(MS), mumps, chronic fatigue syndrome, whiplash, whooping cough, wolff-parkinson-white syndrome, Joint hypermobility'),
('Excess sweating', 'Overactive thyroid,obesity'),
('needing to poo or pee more frequently', 'Overactive thyroid'),
('mood swings', 'Overactive thyroid,Menopause'),
('Difficult sleeping', 'Overactive thyroid'),
('Changes in bowel habits', 'ovarian cancer:Teenagers and young adults'),
('Persistent bloating', 'ovarian cancer:Teenagers and young adults,  Adenomyosis, diverticulitis'),
('Frequent urination', 'ovarian cancer:Teenagers and young adults'),
('Obsession', 'Obsessive compulsive disorder'),
('distress', 'Obsessive compulsive disorder, Alzheimer’s disease'),
('White patches in the mouth', 'oral thrush in adults'),
('Cracks at the corners of the mouth', 'oral thrush in adults'),
('Bone fractures', 'osteoporosis'),
('Loss of height', 'Osteoporosis'),
('Heavy periods', 'Infertility, Adenomyosis'),
('Weight gain', 'Infertility, Rare Conditions'),
('Hair growth', 'Infertility'),
('Persistent itching', 'itchy skin'),
('Dry skin', 'itchy skin, Itchy bottom,Itching'),
('leathery skin', 'itchy skin'),
('Thickened skin', 'itchy skin, Itchy bottom, Itching'),
('scaly skin', 'Itchy Bottom, Itching'),
('Occasional bleeding', 'Itchy Bottom'),
('Cracked skin', 'itchy skin, Itchy bottom, Itching'),
('irritation', 'Itching, Bacterial vaginosis'),
('Digestive problems', 'Rare Conditions'),
('fever', 'rare tumours, Acute myeloid leukaemia: Teenagers and young adults,\nAcute lymphoblastic leukaemia: Teenagers and young adults,Vomiting in Children and Babies, Malaria, Measles, Middle Ear Infection, Mumps, Wilm’s Tumour,Meningitis,Laryngitis, vomiting in children and babies,  Zika virus, Yellow fever, Coronavirus (COVID-19), Chickenpox,Crohn’s Disease, Clostridium Difficile, Vomiting in Children and Babies, Malaria, Measles, Middle Ear Infection, Mumps, Wilm’s Tumour'),
('Unusual bleeding or discharge', 'rare tumours'),
('persistent cough', 'rare tumours, Asbestosis,lung cancer'),
('Night sweats', 'rare tumours'),
('Unexplained lumps or swelling', 'rare tumours'),
('Difficulty swallowing', 'rare tumours, Carcinoid Syndrome, Cervical Cancer'),
('Skin ulcers', 'Raynaud’s phenomenon'),
('Cold fingers or toes', 'Raynaud’s phenomenon'),
('Colour changes in fingers and toes', 'Raynaud’s phenomenon'),
('Numbness or tingling', 'Raynaud’s phenomenon'),
('Vaginal bleeding', 'recurrent miscarriage,Late miscarriage, vaginal cancer, miscarriage, molar pregnancy, womb cancer,Womb (Uterus) cancer'),
('Loss of pregnancy', 'recurrent miscarriage'),
('Cramping', 'recurrent miscarriage'),
('Passing tissue or fluid from the vagina', 'recurrent miscarriage'),
('Uncomfortable sensations in the legs', 'Restless Legs Syndrome'),
('Involuntary jerking of the legs', 'Restless Legs Syndrome'),
('An irresistible urge to move the legs', 'Restless Legs Syndrome'),
('Temporary relief with movement', 'Restless Legs Syndrome'),
('Change in eye color', 'Retinoblastoma'),
('Poor vision', 'Retinoblastoma'),
('sore eye', 'Retinoblastoma'),
('wollen', 'Retinoblastoma'),
('squint', 'Retinoblastoma'),
('swelling of the eye', 'Rhabdomyosarcoma,  angioedema'),
('A lump or swelling', 'Rhabdomyosarcoma,'),
('Difficulty urinating or blood in urine', 'Rhabdomyosarcoma, Benign prostate enlargement'),
('numbness', 'Rhabdomyosarcoma'),
('Persistent pain', 'Rhabdomyosarcoma'),
('Shortness of breath', 'Pulmonary hypertension'),
('Extreme fear or avoidance behavior', 'Phobias'),
('Plantar heel pain', 'Pain in the ball of the foot'),
('Patellofemoral pain syndrome', 'Pain in the ball of the foot'),
('Unexplained weight loss', 'Pancreatic cancer, Prostate cancer, Polymyalgia rheumatica'),
('Pregnancy related symptoms', 'Pregnancy and baby'),
('Persistent low mood after childbirth', 'Postnatal depression'),
('Intense itching in pubic area', 'Pubic lice'),
('Bedsores or skin ulcers', 'Pressure ulcers'),
('Hallucinations or delusions', 'Psychosis, Alzheimer’s disease'),
('Red, scaly skin patches', 'Psoriasis, Psoriatic arthritis, Allergies'),
('Difficulty urinating', 'Prostate cancer, Pelvic organ prolapse'),
('Swollen, painful joints', 'Psoriatic arthritis, Polymyalgia rheumatic'),
('Knee pain', 'Patellofemoral pain syndrome'),
('Urinary incontinence', 'Pelvic organ prolapse, Postnatal depression'),
('Progressive balance and movement problems', 'Progressive supranuclear palsy (PSP)'),
('Flashbacks and nightmares', 'Post-traumatic stress disorder (PTSD)'),
('Headaches, dizziness after injury', 'Post-concussion syndrome'),
('Heel pain', 'Plantar heel pain'),
('Penile sores or lumps', 'Penile cancer, Pubic lice'),
('Severe developmental issues', 'Patau’s syndrome'),
('Tremors and slow movement', 'Parkinson’s disease, Progressive supranuclear palsy (PSP)'),
('Nipple changes (redness, rash, discharge)', 'Paget’s disease of the nipple'),
('Intense fear or panic attacks', 'Panic disorder, Phobias, Post-traumatic stress disorder (PTSD)'),
('Numbness or tingling in hands and feet', 'Peripheral neuropathy, Polymyalgia rheumatica'),
('Changes in mood and behavior', 'Personality disorder, Psychosis, Postnatal depression'),
('Persistent fever in children', 'PIMS (Paediatric Inflammatory Multisystem Syndrome)'),
('Chest pain with breathing', 'Pleurisy, Pneumonia, Pulmonary hypertension'),
('Cough with phlegm or blood', 'Pneumonia, Pulmonary hypertension, Prostate cancer'),
('Muscle weakness or paralysis', 'Polio, Post-polio syndrome, Progressive supranuclear palsy (PSP)'),
('Irregular periods or infertility', 'Polycystic ovary syndrome (PCOS)'),
('Joint and muscle stiffness', 'Polymyalgia rheumatica, Psoriatic arthritis'),
('Rapid heartbeat and dizziness when standing', 'Postural orthostatic tachycardia syndrome (PoTS)'),
('Bleeding during bowel movements', 'Haemorrhoids (piles)'),
('Mucus discharge', 'Haemorrhoids (piles)'),
('Small white eggs (nits) in the hair', 'Head lice and nits'),
('Rash on the back of the neck', 'Head lice and nits'),
('Difficulty hearing the telephone or doorbell', 'Hearing loss'),
('Asking people to repeat themselves', 'Hearing loss'),
('Fainting', 'Heart block,'),
('Swelling in the legs or ankles', 'Heart failure'),
('Irregular Heartbeat', 'Heart palpitations'),
('Lightheadedness', 'Heart palpitations, Dizziness'),
('Be raised', 'Hives'),
('Be on one part of the body', 'Hives'),
('Spread over large areas', 'Hives'),
('Difficult to bath', 'Frozen shoulder'),
('Difficult to dressing', 'Frozen shoulder'),
('Difficult to driving', 'Frozen shoulder'),
('Depression', 'Functional neurological disorder,Hepatitis C'),
('Panic attack', 'Functional neurological disorder'),
('Insomnia', 'Functional neurological disorder'),
('Migraine', 'Functional neurological disorder'),
('Crumbly nails', 'Fungal nail infection'),
('Distortion of the nail', 'Fungal nail infection'),
('Discolouration of the nail', 'Fungal nail infection'),
('Jaundice', 'Gallbladder cancer, Gallstones, Hepatitis A, Hepatitis B, Hepatitis C, Acute cholecystitis, Bile duct cancer'),
('Chills', 'Gallstones'),
('Gurgling Sounds', 'Farting'),
('Tightness or pressure in the throat', 'Globus'),
('Discomfort or irritation in the throat', 'Globus'),
('Persistent mucus that cannot be cleared', 'Globus'),
('lower back pain', 'Fibroids'),
('sharp stabbing pain', 'Fibromyalgia'),
('burning sensation', 'Fibromyalgia'),
('sneezing', 'Flu, Hay fever, Allergic rhinitis, Allergies'),
('Blurred vision', 'Eye cancer, high blood pressure, Hydrocephalus, Hyperglycaemia (high blood sugar), Hypoglycaemia (low blood sugar), Neck injury'),
('Bulging of one eye', 'Eye cancer'),
('Wiggly lines', 'Eye cancer'),
('Eating very little or a large quantity of food', 'Eating disorders'),
('Exercising too much', 'Eating disorders'),
('Hearing loss', 'Earache, Earwax build-up,Labyrinthitis, vertigo, Meniere disease'),
('Swelling around the ear', 'Earache'),
('Hearing loss', 'Labyrinthitis, vertigo, Meniere disease'),
('Bloated stomach', 'Lactose intolerance'),
('Skin may be itchy and develop gradually', 'Lichen planus'),
('mouth tongue or inside the cheeks', 'Lichen planus'),
('Heaviness or tenderness affected areas', 'Lipoedema'),
('bull’s-eye on a dart board', 'Lyme disease'),
('Swelling in legs and ankles', 'Liver disease'),
('Heaviness or tenderness affected areas', 'Lipoedema'),
('Vaginal bleeding', 'Early miscarriage, Ectopic pregnancy'),
('Stomach pain or cramping', 'Early miscarriage,  Non-Hodgkin lymphoma: Children,Anxiety, Kaposi’s sarcoma, Stomach Carcinoid Tumour'),
('Pregnancy symptoms suddenly stopping', 'Early miscarriage'),
('Digestive system', 'Long-term effects of COVID-19'),
('Heart and circulation', 'Long-term effects of COVID-19'),
('Mental health', 'Long-term effects of COVID-19'),
('nails like scarring', 'Licen planus'),
('Tinnitus', 'Earwax build-up'),
('Ear infections', 'Earwax build-up'),
('pain during ovulation', 'Endometriosis'),
('difficulty getting pregnant', 'Endometriosis'),
('Repeated Seizures', 'Epilepsy'),
('Unusual Sensations', 'Epilepsy'),
('Convulsions', 'Epilepsy'),
('Acidreflux', 'Gastro-oesophageal reflux disease (GORD)'),
('Vaginal discharge', 'Genital herpes, Gonorrhoea'),
('Pain in the anus', 'Genital warts,Haemorrhoids (piles)'),
('Pain around the vagina', 'Genital warts'),
('Pain around the penis', 'Genital warts'),
('Lump in the abdomen', 'Germ cell tumours'),
('Difficulty with twisting', 'Golfers elbow'),
('Difficulty with gripping', 'Golfers elbow'),
('A burning sensation when peeing', 'Gonorrhoea'),
('Swelling of the testicles', 'Gonorrhoea'),
('Severe pain in one or more joints', 'Gout'),
('Affecting joints like toes (especially the big toe), ankles, knees, and fingers', 'Gout'),
('Pain when lifting legs in/out a car', 'Greater trochanteric pain syndrome'),
('Pain when climbing stairs', 'Greater trochanteric pain syndrome'),
('Pain sitting with the legs crossed.', 'Greater trochanteric pain syndrome'),
('Red and swollen gums', 'Gum disease, Alzheimer’s disease\ndental abscess'),
('Bleeding gums after brushing your teeth', 'Gum disease'),
('Bad breath (halitosis)', 'Gum disease'),
('Sensitive of painful teeth', 'Gum disease'),
('Swelling in the neck, armpit', 'Hodgkin lymphoma'),
('A painless lump', 'Hodgkin lymphoma: Teenagers and young adults'),
('A lack of emotions', 'Huntington’s disease'),
('Irritability and impulsiveness', 'Huntington’s disease, Hypoglycaemia (low blood sugar)'),
('periods of aggression', 'Huntington’s disease'),
('Drowsiness', 'Hydrocephalus'),
('Difficulty walking', 'Hydrocephalus, Ankle sprain, Bunion(halluxvalgus)'),
('Thirst', 'Hyperglycaemia (high blood sugar)'),
('Dry mouth', 'Hyperglycaemia (high blood sugar), dehydration'),
('Feeling hungry', 'Hypoglycaemia (low blood sugar)'),
('Tingling lips', 'Hypoglycaemia (low blood sugar)'),
('Trembling or shakiness', 'Hypoglycaemia (low blood sugar)'),
('Bleeding during bowel movements', 'Haemorrhoids (piles)'),
('Mucus discharge', 'Haemorrhoids (piles)'),
('Small white eggs (nits) in the hair', 'Head lice and nits'),
('Rash on the back of the neck', 'Head lice and nits'),
('Difficulty hearing the telephone or doorbell', 'Hearing loss'),
('Asking people to repeat themselves', 'Hearing loss'),
('Fainting', 'Heart block,'),
('Swelling in the legs or ankles', 'Heart failure'),
('Irregular Heartbeat', 'Heart palpitations'),
('nosebleeds', 'Nasal and sinus cancer, Nasopharyngeal cancer, acute myeloid leukaemia'),
('mucus draining from the nose, which may be blood-stained', 'Nasal and sinus cancer'),
('a decreased sense of smell', 'Nasal and sinus cancer'),
('swollen glands in the neck', 'Nasal and sinus cancer, Acute lymphoblastic leukaemia: Teenagers and young adults, Acute myeloid leukaemia: Teenagers and young adults'),
('a lump in the neck', 'Nasopharyngeal cancer'),
('hearing loss', 'Nasopharyngeal cancer'),
('a blocked or stuffy nose', 'Nasopharyngeal cancer'),
('neck stiffness', 'Neck injury, Neck problems'),
('difficulty turning your neck', 'Neck injury'),
('muscle spasms', 'Neck injury, Back problems'),
('dizziness', 'Neck injury,Labyrinthitis, vertigo, malnutrition, Minor hard injury, whiplash, Wolff-Parkinson-White Syndrome'),
('pins and needles or numbness in your arm or hand', 'Neck problems'),
('Spinal cord', 'Neuroblastoma: Children'),
('Jerky eyes', 'Neuroblastoma: Children'),
('High blood pressure', 'Neuroblastoma: Children'),
('a dull or aching pain in the top right of the', 'Non-alcoholic fatty liver disease (NAFLD)'),
('unexplained weight loss\n weight loss', 'Non-alcoholic fatty liver disease (NAFLD)'),
('weakness', 'Non-alcoholic fatty liver disease (NAFLD), Stomach Carcinoid Tumour, Carcinoid Tumour, Chronic Fatigue Syndrome, Chronic Kidney Disease, Chronic Myeloid Leukaemia, Cerebral Palsy'),
('painless swelling in a lymph node', 'non-Hodgkin lymphoma'),
('armpit or groin.', 'non-Hodgkin lymphoma'),
('glandular fever', 'non-Hodgkin lymphoma'),
('watery diarrhoea', 'norovirus'),
('Trauma', 'Nosebleed'),
('Heavy bleeding', 'Nosebleed'),
('Infections', 'Nosebleed'),
('Trauma', 'Nosebleed'),
('Heavy bleeding', 'Nosebleed'),
('Infections', 'Nosebleed'),
('severe pain in the abdomen.', 'Abdominal aortic aneurysm'),
('Pain or pulsating feeling in the abdomen', 'Abdominal aortic aneurysm'),
('pain that’s worse during or after moving or exercising', 'Achilles tendinopathy'),
('mild heat', 'Achilles tendinopathy'),
('loss of movement and strength around the ankle and foot', 'Achilles tendinopathy'),
('Oily Skin', 'Acne'),
('Skin Sensitivity', 'Acne'),
('Spots', 'Acne'),
('pale skin', 'acute lymphoblastic leukaemia, acute myeloid leukaemia'),
('unusual and frequent bleeding', 'acute lymphoblastic leukaemia'),
('having repeated infections over a short space of time', 'acute lymphoblastic leukaemia'),
('Swollen lymph glands', 'Acute lymphoblastic leukaemia: Children'),
('aches and pains in the limbs.', 'Acute lymphoblastic leukaemia: Children, Bronchitis(aches and pain only)'),
('bruises', 'Acute lymphoblastic leukaemia: Teenagers and young adults'),
('bruises', 'Acute lymphoblastic leukaemia: Teenagers and young adults'),
('Bruising and Prolonged Bleeding', 'Acute myeloid leukaemia: Children'),
('General Malaise', 'Acute myeloid leukaemia: Children'),
('feeling or being sick', 'Acute pancreatitis'),
('suddenly getting severe pain in the centre of your abdomen (tummy)', 'Acute pancreatitis'),
('low mood', 'Addison’s disease'),
('increased thirst', 'Addison’s disease'),
('Darkened skin', 'Addison’s disease'),
('severe period pain', 'Adenomyosis'),
('a feeling of pressure in your tummy', 'Adenomyosis'),
('yellowing of the eyes and skin', 'alcohol-related liver disease'),
('swelling in the ankles and tummy', 'alcohol-related liver disease'),
('sneezing', 'Allergic rhinitis, Allergies'),
('itchiness', 'Allergic rhinitis'),
('red, itchy, watery eyes', 'Allergies'),
('wheezing and coughing', 'Allergies, Asthma, tonsillitis'),
('worsening of asthma or eczema', 'Allergies'),
('problems with speech and language', 'Alzheimer’s disease'),
('low mood or anxiety', 'Alzheimer’s disease'),
('bleeding from the bottom', 'Anal cancer'),
('itching and pain around the anus', 'Anal cancer'),
('small lumps around the anus', 'Anal cancer'),
('a discharge of mucus from the anus', 'Anal cancer'),
('loss of bowel control', 'Anal cancer'),
('Gastrointestinal', 'Anaphylaxis'),
('Breathing difficulties', 'Anaphylaxis'),
('Cardiovascular', 'Anaphylaxis'),
('feel like a dull pain,ache,heavy,tight,chest', 'angina'),
('spread to your arms, neck, jaw or back', 'angina'),
('be triggered by physical exertion', 'angina'),
('Swelling of the eyes,lips,gentials,hands,feet', 'Angioedema,Varicose Eczema, varicose veins, venous leg ulcer, managing gential symptoms, metacarpal fracture, wrist fracture'),
('mild heat and redness', 'Ankle sprain'),
('loss of movement and strength around the ankle and foot', 'Ankle sprain'),
('Limited Range of Motion', 'Ankle avulsion fracture'),
('arthritis', 'Ankylosing spondylitis'),
('fatigue', 'Ankylosing spondylitis'),
('enthesitis', 'Ankylosing spondylitis'),
('Feeling tired and cold', 'Anorexia nervosa'),
('Reduced bone density', 'Anorexia nervosa'),
('Low weight for age', 'Anorexia nervosa'),
('Avoiding certain foods', 'Anorexia nervosa'),
('restlessness', 'Anxiety'),
('a sense of dread', 'Anxiety'),
('trembling or shaking', 'Anxiety'),
('Panic Disorder', 'Anxiety disorders in children'),
('Obsessive-Compulsive Disorder', 'Anxiety disorders in children'),
('Social Anxiety Disorder (Social Phobia)', 'Anxiety disorders in children'),
('Changes in Bowel Movements', 'Appendicitis'),
('Sudden pain', 'Arterial thrombosis'),
('Paleness(pallor)', 'Arterial thrombosis, Neuroblastoma: Children'),
('coldness', 'Arterial thrombosis'),
('Skin Changes', 'Arterial thrombosis,Blood poisoning (sepsis), Breast cancer(male), Breast cancer(female)'),
('tenderness in the joints', 'Arthritis'),
('stiffness in the joints', 'Arthritis, Back problems(stiffness only)'),
('warm, red skin on your joints', 'Arthritis'),
('Clubbing of fingertips', 'Asbestosis'),
('Clubbing of fingertips', 'Asbestosis'),
('chest tightness', 'Asthma'),
('slurred speech', 'Ataxia, Blood poisoning(sepsis)'),
('Becoming more clumsy', 'Ataxia'),
('Slurred speech', 'Ataxia'),
('Tremors or shaking', 'Ataxia'),
('itching', 'Atopic eczeme'),
('Redness', 'Atopic eczema, Bone Cancer'),
('Dryness', 'Atopic eczeme'),
('Cracking', 'Atopic eczeme'),
('dizziness', 'Atrial fibrillation'),
('Feeling faint', 'Atrial fibrillation'),
('Impulsivity', 'Attention deficit hyperactivity disorder'),
('Restlessness', 'Attention deficit hyperactivity disorder'),
('Difficulty listening', 'Attention deficit hyperactivity disorder'),
('Difficulty with social Interaction', 'autism'),
('Delayed Language Development', 'autism'),
('Limited Nonverbal Communication', 'autism'),
('Hot, burning, shooting or stabbing', 'Back problems'),
('Pins and needles', 'Back problems'),
('Changes in vaginal discharge', 'Bacterial vaginosis'),
('Unpleasant fishy odor', 'Bacterial vaginosis'),
('Rash starting on face', 'Measles'),
('Weak urine flow', 'Benign prostate enlargement'),
('Urgency', 'Benign prostate enlargement, Bladder cancer, Bowel incontinence'),
('Unintentional weight loss', 'Bile duct cancer (cholangiocarcinoma), Kidney cancer, Carcinoid Tumour, Chronic Fatigue Syndrome, Chronic Kidney Disease, Chronic Myeloid Leukaemia, Cirrhosis, Crohn’s Disease, Cancer (Cervical, Carcinoid)'),
('Loss of control', 'Binge eating Disorder'),
('Shame and secrecy', 'Binge eating Disorder'),
('Hoarding food', 'Binge eating Disorder'),
('tense', 'Bipolar disorder'),
('Down, upset or tearful', 'Bipolar disorder'),
('agitated', 'Bipolar disorder'),
('guilt and despair', 'Bipolar disorder'),
('Blood in urine (hematuria)', 'Bladder cancer'),
('Lower back pain', 'Bladder cancer'),
('Feeling of impending doom', 'Blood poisoning(sepsis)'),
('Passing no urine in day', 'Blood poisoning(sepsis)'),
('Muscle pain', 'Blood poisoning(sepsis)'),
('A noticeable lump over a bone', 'Bone Cancer'),
('A weak bone that breaks', 'Bone Cancer'),
('Reduced Movement', 'Bone cancer: Teenagers and young adults'),
('Broken bone', 'Bone cancer: Teenagers and young adults'),
('Blood in the poo', 'Bowel cancer'),
('Changes in bowel habit', 'Bowel cancer'),
('abdominal (tummy) pain', 'Bowel cancer'),
('Leakage', 'Bowel incontinence'),
('Passive Incontinence', 'Bowel incontinence'),
('Soiling', 'Bowel incontinence'),
('A small amount of rectal bleeding', 'Bowel polyps'),
('Ventilator Dependence', 'Brain stem death'),
('Irreversible Brain Damage', 'Brain stem death'),
('Unconsciousness', 'Brain stem death'),
('Seizures(fits)', 'Brain tumour, Brain tumours: Children, Brain tumours: Teenagers and young adults'),
('Mental or Behavioural changes', 'Brain tumour'),
('Feeling very irritated', 'Brain tumours Children'),
('Eye problems', 'Brain tumours: Children, Brain tumours: Teenagers and young adults'),
('Feeling extremely sleepy', 'Brain tumours: Children'),
('Balance and Coordination issues', 'Brain tumours: Teenagers and young adults'),
('Change in size or Shape', 'Breast cancer(male), Breast cancer(female)'),
('Nipple Discharge', 'Breast cancer(male), Breast cancer(female)'),
('Lumps in Armpit', 'Breast cancer(male)'),
('Thickening', 'Breast cancer(female)'),
('Chest infections', 'bronchiectasis'),
('Sore throat', 'Bronchitis'),
('Blocked nose', 'Bronchitis'),
('Preoccupation with food', 'Bulimia nervosa'),
('bingeing', 'Bulimia nervosa'),
('Sleep Disturbances', 'Bulimia nervosa'),
('Mood changes', 'Bulimia nervosa'),
('difficulty swallowing', 'Motor neurone disease(MND), mouth cancer'),
('breathing issues', 'Motor neurone disease(MND)'),
('Persistent sores', 'Mouth cancer'),
('lumps', 'Mouth cancer'),
('unexplained weight loss', 'Mouth cancer'),
('Painful sores in the mouth', 'Mouth ulcer'),
('Difficulty eating or speaking', 'Mouth ulcer'),
('Bone pain', 'Multiple myeloma'),
('frequent infections', 'Multiple myeloma'),
('anemia', 'Multiple myeloma'),
('kidney issues', 'Multiple myeloma'),
('vision issues', 'Multiple Sclerosis (MS)'),
('coordination problems', 'Multiple Sclerosis (MS)'),
('Numbness', 'Multiple Sclerosis (MS), Vitamin B12 or Folate Deficiency Anaemia, wrist fracture'),
('No fetal heartbeat', 'Molar pregnancy'),
('slurred speech', 'Motor neurone disease(MND)'),
('Tremors', 'Multiple System Atrophy (MSA)'),
('muscle rigidity', 'Multiple System Atrophy (MSA)'),
('speech/swallowing problems', 'Multiple System Atrophy (MSA)'),
('blood pressure fluctuations', 'Multiple System Atrophy (MSA)'),
('Swollen salivary glands', 'Mumps'),
('Muscle aches', 'Mumps'),
('Faking or exaggerating illnesses', 'Munchausen’s Syndrome'),
('seeking medical attention unnecessarily', 'Munchausen’s Syndrome'),
('difficulty walking', 'Muscular Dystrophy'),
('frequent falls', 'Muscular Dystrophy'),
('delayed motor skills', 'Muscular Dystrophy'),
('Severe fatigue', 'Chronic Fatigue Syndrome (ME/CFS)'),
('unrefreshing sleep', 'Chronic Fatigue Syndrome (ME/CFS)'),
('concentration issues', 'Chronic Fatigue Syndrome (ME/CFS)'),
('joint/muscle pain', 'Chronic Fatigue Syndrome (ME/CFS)'),
('drooping eyelids', 'Myasthenia Gravis'),
('breathing', 'Myasthenia Gravis'),
('rough bumps on skin', 'Warts and Verrucas'),
('black dots (clotted blood vessels)', 'Warts and Verrucas'),
('pain (verrucas on feet)', 'Warts and Verrucas'),
('Neck pain', 'Whiplash'),
('stiffness', 'Whiplash, Wrist fracture'),
('headaches', 'Whiplash, tonsillitis'),
('shoulder pain', 'Whiplash'),
('Severe coughing fits', 'Whooping cough'),
('\"whoop\" sound when breathing in', 'Whooping cough'),
('Abdominal swelling or mass', 'Wilm’s tumour'),
('blood in urine', 'Wilm’s tumour'),
('wilm’s', 'Wilm’s tumour'),
('Rapid heartbeat', 'Wolff-Parkinson-White Syndrome'),
('Vaginal bleeding (post-menopause or between periods)', 'Womb (Uterus) cancer'),
('abnormal discharge', 'Womb (Uterus) cancer'),
('Severe pain', 'Wrist Fracture'),
('deformity', 'Wrist Fracture'),
('Numbness in fingers', 'Wrist Fracture'),
('Hand pain', 'Metacarpal fracture'),
('bruising', 'Metacarpal fracture, wrist fracture'),
('difficulty moving fingers', 'Metacarpal fracture'),
('fluid drainage', 'Middle ear infection'),
('hearing problems', 'Middle ear infection, Deafblindness'),
('irritability (in children)', 'Middle ear infection'),
('Intense headache', 'migraine'),
('light/sound sensitivity', 'migraine'),
('visual disturbances', 'migraine'),
('cramping', 'Miscarriage'),
('Unusual bleeding', 'Vulval cancer'),
('Balance issues', 'vertigo'),
('Hearing loss', 'vertigo'),
('weakness', 'Vitamin B12 or Folate Deficiency Anaemia'),
('Pale skin', 'Vitamin B12 or Folate Deficiency Anaemia'),
('Memory loss', 'Vitamin B12 or Folate Deficiency Anaemia'),
('dehydration', 'Vomiting in adults, vomiting in children and babies'),
('irritability', 'Vomiting in children and babies'),
('Skin changes', 'Vulval cancer'),
('Unusual bleeding', 'Vulval cancer'),
('Chills', 'Malaria'),
('sweating', 'Malaria'),
('discharge', 'Managing gential symptoms'),
('pain during urination', 'Managing gential symptoms'),
('sores or lesions', 'Managing gential symptoms'),
('rash starting on face', 'Measles'),
('runny nose', 'Measles, whooping cough'),
('red and watery eyes.', 'Measles'),
('Stiff neck', 'Meningitis'),
('high fever', 'Meningitis'),
('severe headache', 'Meningitis'),
('sensitivity to light', 'Meningitis, minor head injury'),
('confusion', 'Meningitis, minor head injury'),
('Vertigo', 'Meniere’s disease'),
('ringing in ears (tinnitus)', 'Meniere’s disease'),
('ear pressure', 'Meniere’s disease'),
('Blistering (small fluid-filled bumps)', 'Sunburn'),
('Dehydration', 'Sunburn'),
('hot skin to the touch', 'Sunburn'),
('No signs of struggle or distress', 'Sudden infant death syndrome'),
('pale skin (cyanosis) after death', 'Sudden infant death syndrome'),
('Periods of apnea (breathing pauses) before death (though not always observed)', 'Sudden infant death syndrome'),
('Feeling of catching or grinding when moving the shoulder', 'Subacromial pain syndrome'),
('Difficulty moving the arm, especially above shoulder height', 'Subacromial pain syndrome'),
('loss of balance, or coordination issues', 'stroke'),
('Sudden trouble seeing in one or both eyes', 'stroke'),
('Sudden confusion, trouble speaking, or understanding speech', 'stroke'),
('Low blood pressure (shock)', 'Streptococcus A (strep A)'),
('Strawberry-like red tongue', 'Streptococcus A (strep A)'),
('Tiny red spots (petechiae) on the roof of the mouth', 'Streptococcus A (strep A)'),
('indigestion', 'Stomach ulcer'),
('yellowing of the skin and whites of the eyes (jaundice)', 'Stomach cancer'),
('lumpiness and swelling in your stomach (caused by a build-up of fluid)', 'Stomach cancer'),
('blood in your stools, or black stools', 'Stomach cancer'),
('pain in your stomach or breastbone', 'Stomach cancer'),
('feeling bloated after eating', 'Stomach cancer'),
('Heart burn', 'Stomach cancer'),
('trapped wind and frequent burping', 'Stomach cancer'),
('stiffness', 'Spinal stenosis'),
('weakness', 'Spinal stenosis'),
('hydracephalus (excess fluid on the brain)', 'Spina bifida'),
('bowel incontinence, leading to constipation', 'Spina bifida'),
('repeat or frequent urinary tract infections', 'Spina bifida'),
('urinary retention', 'Spina bifida'),
('urinary incontinence', 'Spina bifida'),
('weakness', 'Spina bifida'),
('nasal/throat blockage', 'Soft tissue sarcomas'),
('Lower tummy pain', 'Soft tissue sarcomas: Teenagers and young adults'),
('blood in urine', 'Soft tissue sarcomas: Teenagers and young adults'),
('painful tummy', 'Soft tissue sarcomas: Teenagers and young adults'),
('Painless lump', 'Soft tissue sarcomas: Teenagers and young adults'),
('aching pain in muscles or joints', 'Soft tissue sarcomas'),
('Persistent pain if the tumor presses on nerves or organs', 'Soft tissue sarcomas'),
('Sandpaper-like texture (scarlet fever)', 'Skin rashes in children'),
('Blisters that crust over (chickenpox', 'Skin rashes in children'),
('Red spots or bumps that may start on the face and spread', 'Skin rashes in children'),
('Raised bumps or blisters', 'Skin rashes in children'),
('A new, dark streak under a fingernail or toenail (can mimic a bruise).', 'Skin cancer (melanoma)'),
('A sore that doesn’t heal', 'Skin cancer (melanoma)'),
('bleeding or becoming crusty', 'Skin cancer (melanoma)'),
('new mole or a change in the appearance of an existing mole', 'Skin cancer (melanoma)'),
('vasculitis (inflammation of blood vessels)', 'Sjogren’s syndrome'),
('sensitivity to light (photophobia)', 'Sjogren’s syndrome'),
('mucus discharge from your eyes', 'Sjogren’s syndrome'),
('burning or stinging eyes', 'Sjogren’s syndrome'),
('difficulty speaking', 'Sjogren’s syndrome'),
('difficulty swallowing and chewing', 'Sjogren’s syndrome'),
('dry mouth and eyes', 'Sjogren’s syndrome'),
('have difficulty feeding', 'Sinusitis'),
('bad breath (halitosis)', 'Sinusitis'),
('a high temperature (fever) of 38°C (100.4°F) or more', 'Sinusitis'),
('toothache', 'Sinusitis'),
('a green or yellow discharge from your nose', 'Sinusitis'),
('sudden vision loss, or changes in your vision', 'Sickle cell disease'),
('priapism – a painful erection lasting two hours or more', 'Sickle cell disease'),
('weakness on one or both sides of your body', 'Sickle cell disease'),
('drowsiness, confusion, or slurred speech', 'Sickle cell disease'),
('infections, and anaemia', 'Sickle cell disease'),
('rash usually appears on side of your body', 'Shingles'),
('has severe neck pain or cannot move their head', 'Severe head injury'),
('has signs of damage to their skull, like a dent in their head', 'Severe head injury'),
('hit their head with force, like being hit by a car', 'Severe head injury'),
('is struggling to walk, balance, speak, write, or understand other people', 'Severe head injury'),
('is unresponsive', 'Severe head injury'),
('a soft spot on a baby’s head that bulges', 'Sepsis'),
('“sunken” eyes', 'Sepsis'),
('stiffness in the neck, especially when trying to look up or down', 'Sepsis'),
('a fast heartbeat', 'Sepsis'),
('faint', 'Sepsis'),
('slurred speech', 'Sepsis'),
('severe breathlessness', 'Sepsis'),
('cold, clammy and pale or mottled skin', 'Sepsis'),
('less urine production than normal – for example, not urinating for a day', 'Sepsis'),
('black, green or bloody vomit', 'Sepsis'),
('feel tired and sleep more than normal (hypersomnia)', 'Seasonal affective disorder (SAD)'),
('have an increased appetite and eat more than usual (hyperphagia)', 'Seasonal affective disorder (SAD)'),
('A reduced sex drive', 'Seasonal affective disorder (SAD)'),
('feelings of despair', 'Seasonal affective disorder (SAD)'),
('low mood , a loss of pleasure or interest in normal, everyday activities', 'Seasonal affective disorder (SAD)'),
('a prominent ribcage', 'scoliosis'),
('one shoulder or hip being more prominent than the other', 'scoliosis'),
('a visibly curved spine', 'Scoliosis'),
('muscle spasms in the back', 'Sciatica'),
('burning sensations', 'Sciatica'),
('a weakness in the leg or foot', 'Sciatica'),
('leg pain, often this feels worse than back pain', 'Sciatica'),
('lower back pain', 'Sciatica'),
('Changes in thinking and behaviour', 'Schizophrenia'),
('Recurring diarrhoea which may contain blood, mucus or pus', 'Ulcerative colitis'),
('extreme tiredness (fatigue)', 'Ulcerative colitis, tonsillitis'),
('weight loss', 'Ulcerative colitis'),
('irritated and red eyes', 'Ulcerative colitis'),
('muscle cramps', 'Underactive thyroid'),
('brittle hair and nails', 'Underactive thyroid'),
('irregular periods or heavy periods', 'Underactive thyroid'),
('low-pitched and hoarse voice', 'Underactive thyroid'),
('thinned or partly missing eyebrows', 'Underactive thyroid'),
('Leakage when sneezing, coughing, laughing, or lifting heavy objects', 'Urinary incontinence'),
('Small amounts of urine loss due to pressure on the bladder', 'Urinary incontinence'),
('Constant dribbling of urine', 'Urinary incontinence'),
('Weak or intermittent urine stream', 'Urinary incontinence'),
('Frequent urinary tract infections (UTIs)', 'Urinary incontinence in women'),
('Small amounts of urine leakage without warning', 'Urinary incontinence in women'),
('Involuntary loss of urine immediately after feeling the urge', 'Urinary incontinence in women'),
('need to pee more often than usual', 'Urinary tract infection (UTI)'),
('pain or discomfort when peeing', 'Urinary tract infection (UTI)'),
('feeling generally unwell, achy and tired', 'Urinary tract infection (UTI)'),
('urine that’s cloudy, foul-smelling or contains blood', 'Urinary tract infection (UTI)'),
('shivering and chills', 'Urinary tract infection (UTI)'),
('pain in your sides or back', 'Urinary tract infection (UTI)'),
('can see blood in pee', 'Urinary tract infection (UTI)'),
('not gaining weight', 'Urinary tract infection (UTI) in children'),
('yellowing of the skin and whites of the eyes (jaundice) in very young children', 'Urinary tract infection (UTI) in children'),
('pain or a burning sensation when peeing', 'Urinary tract infection (UTI) in children'),
('unpleasant-smelling pee', 'Urinary tract infection (UTI) in children'),
('change in appearance within 24 hours', '(urticaria) hives'),
('s size from a few millimetres to the size of a hand', '(urticaria) hives'),
('Swelling of the affected area', '(urticaria) hives'),
('Sudden outbreak of red, itchy welts', '(urticaria) hives'),
('difficulty with gripping.', 'Tennis elbow'),
('difficulty with twisting movements such as opening jars.', 'Tennis elbow'),
('restriction in movement at the elbow.', 'Tennis elbow'),
('tenderness when touching the area.', 'Tennis elbow'),
('dull ache', 'Testicular cancer'),
('sharp pain in your testicles or scrotum', 'Testicular cancer'),
('feeling of heaviness in your scrotum', 'Testicular cancer'),
('change in the texture or increase in firmness of a testicle', 'Testicular cancer'),
('difference between one testicle and the other', 'Testicular cancer'),
('Painless lump or swelling in one testicle', 'Testicular cancer: Teenagers and young adults'),
('Breast enlargement or tenderness (due to hormonal changes)', 'Testicular cancer: Teenagers and young adults'),
('Swelling in the legs (due to lymph blockage)', 'Testicular cancer: Teenagers and young adults'),
('general malaise', 'Testicular cancer: Teenagers and young adults'),
('sudden, severe pain in a testicle', 'Testicular lumps and swellings'),
('testicle pain that has lasted more than an hour or continues when you’re resting', 'Testicular lumps and swellings'),
('change in the shape of your testicles', 'Testicular lumps and swellings'),
('change in the way your testicles feel', 'Testicular lumps and swellings'),
('1 testicle that has become bigger than the other', 'Testicular lumps and swellings'),
('Dry mouth', 'Thirst'),
('Frequent desire to drink water', 'Thirst'),
('feeling dehydrated or lightheaded', 'Thirst'),
('Cracked or dry lips', 'Thirst'),
('wetting the bed', 'Threadworms'),
('irritated skin around the anus', 'Threadworms'),
('white vaginal discharge (often like cottage cheese), which does not usually smell', 'Thrush'),
('itching and irritation around the vagina', 'Thrush'),
('soreness and stinging during sex or when you pee', 'Thrush'),
('difficulty pulling back the foreskin', 'Thrush'),
('white or yellow discharge', 'Thrush'),
('unexplained hoarseness that doesn’t get better after a few weeks', 'Thyroid cancer'),
('a sore throat or difficulty swallowing that doesn’t get better', 'Thyroid cancer, tonsillitis'),
('pain in your neck', 'Thyroid cancer'),
('Unexplained weight changes', 'Thyroid cancer'),
('Visible deformity (if the bone is displaced', 'Thumb fracture'),
('Thumb appears shorter or misaligned', 'Thumb fracture'),
('Numbness or tingling in the thumb', 'Thumb fracture'),
('Severe pain in the thumb, especially after injury', 'Thumb fracture'),
('Swollen lymph nodes in the neck', 'Thyroid cancer: Teenagers and young adults'),
('Chronic cough not related to a cold', 'Thyroid cancer: Teenagers and young adults'),
('Unexplained fatigue or weight changes', 'Thyroid cancer: Teenagers and young adults'),
('blistering', 'Tick bites'),
('bruising', 'Tick bites'),
('itchiness', 'Tick bites'),
('buzzing', 'Tinnitus'),
('humming', 'Tinnitus'),
('grinding', 'Tinnitus'),
('noises that beat in time with your pulse', 'Tinnitus'),
('bad breath', 'Tonsillitis'),
('white pus-filled spots on the tonsils', 'Tonsillitis'),
('loss of voice or changes to your voice', 'Tonsillitis'),
('tooth sensitivity – you may feel tenderness or pain when eating or drinking something hot, cold or sweet', 'tonsillitis'),
('an unpleasant taste in your mouth', 'tonsillitis'),
('grey, brown or black spots appearing on your teeth', 'tonsillitis'),
('toothache – either continuous pain keeping you awake or occasional sharp pain without an obvious cause', 'tonsillitis'),
('eye blinking', 'Tourette’s syndrome'),
('neck and head jerks', 'Tourette’s syndrome'),
('arm and leg movements', 'Tourette’s syndrome'),
('pinching', 'Tourette’s syndrome'),
('kicking', 'Tourette’s syndrome');